# Generated by Django 3.1.4 on 2022-07-18 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=100, unique=True, verbose_name='Actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Producto')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.FloatField()),
                ('precio_total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=15, unique=True, verbose_name='R.U.C')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Proveedor')),
                ('direccion', models.CharField(max_length=150, verbose_name='Direccion')),
                ('contacto', models.CharField(max_length=150, null=True)),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono/fax')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=10, unique=True, verbose_name='Rol')),
            ],
            options={
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='Cedula')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('telefono', models.CharField(max_length=14, null=True, verbose_name='Telefono')),
                ('email', models.EmailField(max_length=254)),
                ('fecha_registro', models.DateField(auto_now_add=True, null=True)),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControlPersonal.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripcion')),
                ('fecha_carga', models.DateField(auto_now_add=True)),
                ('valor', models.FloatField(default=0)),
                ('precio_total', models.FloatField(default=0, null=True)),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('cantidad', models.FloatField(default=0)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControlPersonal.actividad')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControlPersonal.persona')),
            ],
            options={
                'verbose_name_plural': 'Cuentas',
            },
        ),
    ]
