# Generated by Django 3.1.4 on 2022-07-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlPersonal', '0005_producto_producto_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(default='PRO-0', max_length=7, unique=True, verbose_name='Codigo producto'),
        ),
    ]
