# Generated by Django 3.1.4 on 2022-07-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlPersonal', '0006_producto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='producto_proveedor',
            field=models.ManyToManyField(related_name='productos', to='ControlPersonal.Proveedor'),
        ),
    ]
