# Generated by Django 3.1.4 on 2022-07-20 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ControlPersonal', '0011_cuenta_producto_cuenta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='producto_cuenta',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='producto_cuenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ControlPersonal.producto'),
        ),
    ]
