# Generated by Django 3.1.4 on 2022-07-20 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ControlPersonal', '0013_auto_20220719_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='valor',
        ),
    ]
