# Generated by Django 3.1.4 on 2022-07-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlPersonal', '0014_auto_20220719_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_total',
            field=models.FloatField(default=0),
        ),
    ]
