# Generated by Django 3.1.4 on 2022-07-20 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ControlPersonal', '0016_producto_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(choices=[('LIMPIEZA', 'limpeza'), ('RECOLECCION', 'recoleccioin')], default='RECOLECCION', max_length=15)),
                ('cantidad', models.IntegerField(default=0)),
                ('invercion', models.FloatField(default=0)),
                ('stock', models.IntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControlPersonal.producto')),
            ],
        ),
    ]
