# Generated by Django 3.1.4 on 2022-07-20 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ControlPersonal', '0017_bodega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='producto_cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControlPersonal.producto'),
        ),
    ]
