# Generated by Django 3.1.4 on 2022-07-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlPersonal', '0018_auto_20220720_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=7, unique=True, verbose_name='Codigo producto'),
        ),
    ]
