# Generated by Django 3.1.4 on 2022-08-04 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ControlPersonal', '0020_remove_producto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('time_in', models.TimeField(auto_now_add=True, verbose_name='Hora entrada')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControlPersonal.persona')),
            ],
        ),
    ]
