# Generated by Django 3.1.4 on 2022-08-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlPersonal', '0021_auto_20220804_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencia',
            options={'verbose_name_plural': 'Asistencias'},
        ),
        migrations.AddField(
            model_name='asistencia',
            name='number_hour',
            field=models.FloatField(default=0.0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='time_out',
            field=models.TimeField(auto_now=True, verbose_name='Hora salida'),
        ),
    ]
