# Generated by Django 3.1.4 on 2022-09-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlPersonal', '0026_auto_20220903_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='status_out',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
