# Generated by Django 3.1.4 on 2022-09-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlPersonal', '0027_asistencia_status_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='status_out',
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='time_out',
            field=models.TimeField(blank=True, verbose_name='Hora salida'),
        ),
    ]
